image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

environment:
  matrix:
    - TOOLSET: vs2017


clone_depth: 1

# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
init:
    - git config --global core.autocrlf input


clone_script:
  - cmd: git clone https://github.com/TheCherno/Hazel.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

build:
  verbosity: quiet



build_script:
  - GenerateProjects.bat
